print("---------------------------------------------------")
print("*                                                 *")
print("*          Sistema de média de notas              *")
print("*                                                 *")
print("---------------------------------------------------")
print(" ")
numero_1 = int(input("           Digite a Primeira Nota: "))
numero_2 = int(input("           Digite a Segunda Nota:  "))
numero_3 = int(input("           Digite a Tereceira Nota: "))
numero_4 = int(input("           Digite a Quarta Nota: "))
soma = ((numero_1 + numero_2 + numero_3 + numero_4) / 4)
print("            ------------------------")
print("")
print("               Sua media é:",soma)
print("")
print("            ------------------------")
if soma>=7:
  print("Uhuuuuulllllll o/ Você foi APROVADO")
else:
  print("")
  print("  Quem mandou não estudar ? Você foi REPROVADA")